"""Exact verified chunk-metadata deltas; generated by generate-map-metadata-deltas.py."""

VARIANTS = (
    ('TazUO.dll', 'aac6afae48a00ddeef711238b5e84491ae4b9bd0aff89e91fb4fc956fc0b0b76', '8e012a25d86f3e89d5f6f171a83418d48dfe08fad5696e3518293f8da0eb74f6', 'tazuo-5.2-map-metadata-client.patch.b64'),
    ('ClassicUO.Assets.dll', '84340a487aeae33c0f17ae1b20a0c8d1b54122d1e23801e5a582452c7db905c9', 'ef63b2e0b1205d1c441cf5003ccbb5d1ce045e186f63f8e80cae7bfc65f22749', 'tazuo-5.2-map-metadata-assets-music.patch.b64'),
    ('TazUO.dll', 'fe64075b3ec0ebbea7d07ffc8b4a010e53ba7767018491b6370026d86e7c3a80', '6eadec3d80c3c3ee7dcf6c054ad9c195aca5183da26e856d0ef20de79ebfcc8a', 'tazuo-5.2-map-metadata-client-render.patch.b64'),
    ('ClassicUO.Assets.dll', '1dd53cf0eea718aefeda33fba105c9797b138188be22562b47548c310524100d', 'cd1845750cd2b2f2c2b73c933fb44b188d6d15e5f3580e60411d15ac31cfc0e4', 'tazuo-5.2-map-metadata-assets.patch.b64'),
    ('TazUO.dll', 'fe1c83cfde7de0afaa00c0f9cccc7a96af4297dfc551ce724500b017be4c03ed', '112f86ca39e99d0171feedc057130f6c0c7b9b1e780f444068d04e71a4962764', 'tazuo-5.2-map-metadata-client-resource.patch.b64'),
    ('ClassicUO.Assets.dll', 'b10baebafdcc4e006dfb347453928c686a5508136e90214d2e3b0fa146b35f14', 'f4e554badfe284e63b5183682de87a5534017e1ceb870c5ee024194151f4eb19', 'tazuo-5.2-map-metadata-assets-resource-music.patch.b64'),
    ('TazUO.dll', '5272bc8a31a534a4530b409db5efba39dd9e630e33761437e2133d7a9bce4d36', 'd9eac1414059a21d9b29e489c8afbe1490bad73d964e0baaa8437715f12c7fa8', 'tazuo-5.2-map-metadata-client-resource-render.patch.b64'),
    ('ClassicUO.Assets.dll', '764e7cba68a58c3a1ef3d72013abcf866275b824ba3a662939d7a7630af2b20c', '4714459d56abd1da40eb2978a3f927b753eaed4e87a8f224f6c9e48dec436c05', 'tazuo-5.2-map-metadata-assets-resource.patch.b64'),
)
