const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:850},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.route('https://app.memento.local/**',async route=>{
  const filename=path.basename(new URL(route.request().url()).pathname)||'index.html';
  const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png'};
  await route.fulfill({contentType:types[path.extname(filename)],body:fs.readFileSync(path.join(__dirname,'../app/src/main/assets/ui',filename))});
 });
 await page.addInitScript(()=>{
  window.calls=[];window.Memento={call(id,op,args){window.calls.push({op,args:JSON.parse(args)});let result={};
   if(op==='native_state')result={alive:true,installed:true,status:'Realm runtime ready',free_bytes:24*1073741824};
   if(op==='client_native_state')result={alive:false,installed:true,status:'TazUO is ready to launch.',launch:{sdl_graphics:window.graphicsReport}};
   if(op==='state')result={running:false,build:{revision:'916d1ec666376ef44366c986befa3200deb93eb0',ref:'main'},client:{executable:'Client/TazUO.exe',architecture:'x64',dotnet_version:'10.0.0'},jobs:[]};
   if(op==='logs')result={text:'Memento: ready\n',names:['runtime.log','server.log']};
   setTimeout(()=>window.nativeReply(id,{ok:true,result}),0);
  }};
 });
 await page.goto('https://app.memento.local/index.html');await page.waitForTimeout(200);
 fs.mkdirSync('ui-reports',{recursive:true});
 await page.screenshot({path:'ui-reports/realm-landscape.png',fullPage:true});
 await page.locator('[data-tab="client"]').click();
 await page.locator('[data-action="controller_open"]').click();
 if(!await page.evaluate(()=>window.calls.some(c=>c.op==='controller_open')))throw Error('Controller action not connected');
 if(!await page.locator('#gump-space').isChecked())throw Error('Requested world layout must default on');
 if(await page.locator('#fps').inputValue()!=='30')throw Error('Cooler frame target must default to 30');
 if(await page.locator('#audio-driver').inputValue()!=='wasapi'||!await page.locator('#client-acceleration').isChecked())throw Error('Optimized launch defaults missing');
 if(!await page.locator('#smooth-audio').isChecked())throw Error('Smooth audio must default on');
 if(!await page.locator('#frame-budget').isChecked())throw Error('Frame budget must default on');
 if(!await page.locator('#music-cache').isChecked())throw Error('Music cache must default on');
 if(await page.locator('#render-trace').isChecked())throw Error('Render tracing must default off');
 if(await page.locator('#managed-diagnostics').isChecked())throw Error('Managed diagnostics must default off');
 if(await page.locator('#sdl-graphics-fixes').isChecked())throw Error('FEX must start with original graphics libraries');
 await page.evaluate(async()=>{window.graphicsReport={active_version:'3.4.16',action:'updated_known_tazuo_5.2_pair'};await refresh();});
 await page.waitForFunction(()=>document.getElementById('sdl-graphics-status').textContent.includes('3.4.16 active'));
 await page.evaluate(async()=>{window.graphicsReport={active_version:'unrecognized',action:'unchanged_unrecognized_libraries'};await refresh();});
 await page.waitForFunction(()=>document.getElementById('sdl-graphics-status').textContent.includes('left as imported'));
 await page.evaluate(()=>localStorage.setItem('launch',JSON.stringify({managed_diagnostics:true,render_trace:true,sdl_graphics_fixes:true,client_memory_compatibility:true,renderer:'turnip',resolution:'1280x720',presentation_mode:'native_surface',display_fps:60,audio:false,gump_space:true})));
 await page.reload();await page.locator('[data-tab="client"]').click();
 if(await page.locator('#render-trace').isChecked()||await page.locator('#managed-diagnostics').isChecked()||await page.locator('#sdl-graphics-fixes').isChecked())throw Error('Legacy runtime experiments must reset');
 if(await page.locator('#fps').inputValue()!=='30')throw Error('Old transport-only 60 target must migrate to cooler default');
 if(await page.locator('#audio').isChecked()||await page.locator('#presentation').inputValue()!=='native_surface'||!await page.locator('#gump-space').isChecked())throw Error('Upgrade must preserve unrelated options');
 await page.locator('#resolution').selectOption('800x600');
 if(await page.locator('#gump-space').isChecked())throw Error('Other resolutions must opt out of fixed layout');
 await page.locator('#gump-space').check();
 if(await page.locator('#resolution').inputValue()!=='1280x720')throw Error('Gump space must select full 1280 canvas');
 await page.reload();await page.locator('[data-tab="client"]').click();
 if(!await page.locator('#gump-space').isChecked())throw Error('Layout selection did not persist');
 await page.locator('[data-action="client_start"]').click();await page.waitForTimeout(50);
 if(!await page.evaluate(()=>window.calls.some(c=>c.op==='client_start'&&c.args.runtime_backend==='fex-arm64ec-1'&&c.args.managed_diagnostics===false&&c.args.render_trace===false&&c.args.sdl_graphics_fixes===false&&c.args.audio_driver==='wasapi'&&c.args.proot_acceleration===true&&c.args.music_cache===true&&c.args.frame_budget===true&&c.args.smooth_audio===true)))throw Error('Default options missing from native launch');
 await page.locator('#fps').selectOption('60');
 await page.locator('#audio-driver').selectOption('directsound');
 await page.locator('#client-acceleration').uncheck();
 await page.locator('#music-cache').uncheck();
 await page.locator('#frame-budget').uncheck();
 await page.locator('#smooth-audio').uncheck();
 await page.locator('#render-trace').check();
 await page.locator('#managed-diagnostics').check();
 await page.locator('#sdl-graphics-fixes').uncheck();
 await page.reload();await page.locator('[data-tab="client"]').click();
 if(await page.locator('#sdl-graphics-fixes').isChecked())throw Error('Original graphics library choice did not persist');
 if(await page.locator('#fps').inputValue()!=='60')throw Error('Explicit 60 FPS choice must persist');
 if(!await page.locator('#render-trace').isChecked())throw Error('Render trace choice did not persist');
 await page.locator('[data-action="client_start"]').click();await page.waitForTimeout(50);
 if(!await page.evaluate(()=>window.calls.some(c=>c.op==='client_start'&&c.args.runtime_backend==='fex-arm64ec-1'&&c.args.managed_diagnostics===true&&c.args.render_trace===true&&c.args.sdl_graphics_fixes===false&&c.args.audio_driver==='directsound'&&c.args.proot_acceleration===false&&c.args.music_cache===false&&c.args.frame_budget===false&&c.args.smooth_audio===false)))throw Error('Selected options missing from native launch');
 if(!await page.evaluate(()=>JSON.parse(localStorage.getItem('launch')).gump_space))throw Error('Launch option missing');
 await page.screenshot({path:'ui-reports/client-landscape.png',fullPage:true});
 await page.setViewportSize({width:412,height:915});await page.screenshot({path:'ui-reports/client-phone.png',fullPage:true});
 for(const tab of ['realm','client','saves','journal']){
  await page.locator(`[data-tab="${tab}"]`).click();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error(tab+' overflows narrow viewport');
 }
 if(errors.length)throw Error(errors.join('\n'));
 console.log('Four tabs, native controller action, FEX migration and diagnostic options, phone/landscape layouts passed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
