const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const settingsFixture=JSON.parse(require('child_process').execFileSync('python3',['-c',"import json,sys;from pathlib import Path;sys.path.insert(0,'backend');from server_settings import fields;print(json.dumps({'revision':'first','fields':[f for f,_ in fields(Path('tests/fixtures/memento-settings.cs').read_text())],'can_undo':False,'running':False}))"],{cwd:path.join(__dirname,'..'),encoding:'utf8'}));
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:850},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.route('https://app.memento.local/**',async route=>{
  const filename=path.basename(new URL(route.request().url()).pathname)||'index.html';
  const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png'};
  await route.fulfill({contentType:types[path.extname(filename)],body:fs.readFileSync(path.join(__dirname,'../app/src/main/assets/ui',filename))});
 });
 await page.addInitScript((settingsFixture)=>{
  window.settingsFixture=settingsFixture;window.mockJobs=[];window.backupReport=[{name:'memento-world-2.zip',file:'exports/memento-world-2.zip',bytes:2000,created_at:1790871000,reason:'Before restore'},{name:'memento-world-1.zip',file:'exports/memento-world-1.zip',bytes:1000,created_at:1790870000,reason:'Manual backup',exported_at:1790870100}];
  window.calls=[];window.Memento={call(id,op,args){window.calls.push({op,args:JSON.parse(args)});let result={};
   if(op==='session_play'&&window.holdSession){window.nativeReport={session_busy:true,session_cancellable:true,session_seconds:12,session_status:'Starting server · waiting for the world to be ready…'};window.heldSession=id;return;}
   if(op==='session_play'&&window.sessionFailure){setTimeout(()=>window.nativeReply(id,{ok:false,error:window.sessionFailure}),0);return;}
   if(op==='client_start'||op==='session_play')window.clientActive=true;
   if(op==='native_state')result={alive:true,installed:true,status:'Realm runtime ready',version:'0.2.9',free_bytes:24*1073741824,...window.nativeReport};
   if(op==='client_native_state')result={alive:!!window.clientActive,display_ready:!!window.clientActive,installed:true,status:'TazUO is ready to launch.',launch:{sdl_graphics:window.graphicsReport}};
   if(op==='state')result={running:false,ready:false,build:{revision:'916d1ec666376ef44366c986befa3200deb93eb0',ref:'main'},client:{executable:'Client/TazUO.exe',architecture:'x64',dotnet_version:'10.0.0'},jobs:[],...window.realmReport};
   if(op==='state')result.jobs=[...result.jobs,...window.mockJobs];
   if(op==='backups')result={entries:window.backupReport,total_bytes:window.backupReport.reduce((sum,entry)=>sum+entry.bytes,0)};
   if(op==='backup_preview')result={name:JSON.parse(args).name,backup:JSON.parse(args).name,folders:['Info','Saves','Backups'],bytes:2000,files:12,unpacked_bytes:4000};
   if(op==='settings_read')result=structuredClone(window.settingsFixture);
   if(['settings_save','settings_undo','save_backup','delete_backup','prune_backups','restore_world'].includes(op)){
    if(op==='settings_save'){window.previousSettings=structuredClone(window.settingsFixture);for(const field of window.settingsFixture.fields)if(Object.hasOwn(JSON.parse(args).changes,field.name))field.value=JSON.parse(args).changes[field.name];window.settingsFixture.revision+='x';window.settingsFixture.can_undo=true;}
    if(op==='settings_undo')window.settingsFixture=window.previousSettings;
    if(op==='delete_backup')window.backupReport=window.backupReport.filter(entry=>entry.name!==JSON.parse(args).name);
    if(op==='restore_world')window.nativeReport={alive:true,session_busy:false};
    result={id:'task-'+(window.mockJobs.length+1)};window.mockJobs.push({...result,status:'done',message:'Complete',result:{message:'Complete',file:op==='save_backup'?'exports/memento-world-2.zip':undefined}});
   }
   if(op==='session_close'||op==='session_cancel'){window.clientActive=false;window.nativeReport={alive:false,session_busy:false};result={message:'Session saved and closed.'};if(window.heldSession){window.nativeReply(window.heldSession,{ok:false,error:'Launch cancelled. Saving and closing the session…'});window.heldSession=null;window.holdSession=false;}}
   if(op==='logs')result={text:'Memento: ready\n',names:['runtime.log','server.log']};
   setTimeout(()=>window.nativeReply(id,{ok:true,result}),0);
  }};
 },settingsFixture);
 await page.goto('https://app.memento.local/index.html');await page.waitForTimeout(200);
 fs.mkdirSync('ui-reports',{recursive:true});
 await page.screenshot({path:'ui-reports/realm-landscape.png',fullPage:true});
 await page.locator('[data-tab="client"]').click();
 if(await page.locator('#client-options').evaluate(node=>node.open))throw Error('Client options must start collapsed');
 if(!await page.evaluate(()=>['renderer','resolution','presentation','fps','gump-space','audio','audio-driver','smooth-audio','client-acceleration','frame-budget','music-cache','sdl-graphics-fixes','render-trace','managed-diagnostics'].every(id=>document.getElementById(id).closest('#client-options'))))throw Error('Client controls escaped the options dropdown');
 await page.locator('#client-options > summary').click();
 await page.locator('[data-action="controller_open"]').click();
 if(!await page.evaluate(()=>window.calls.some(c=>c.op==='controller_open')))throw Error('Controller action not connected');
 if(!await page.locator('#gump-space').isChecked())throw Error('Requested world layout must default on');
 if(await page.locator('#fps').inputValue()!=='30')throw Error('Cooler frame target must default to 30');
 if(await page.locator('#audio-driver').inputValue()!=='wasapi'||!await page.locator('#client-acceleration').isChecked())throw Error('Optimized launch defaults missing');
 if(!await page.locator('#smooth-audio').isChecked())throw Error('Smooth audio must default on');
 if(!await page.locator('#frame-budget').isChecked())throw Error('Frame budget must default on');
 if(!await page.locator('#music-cache').isChecked())throw Error('Music cache must default on');
 if(await page.locator('#render-trace').isChecked())throw Error('Render tracing must default off');
 if(await page.locator('#managed-diagnostics').isChecked())throw Error('Managed diagnostics must default off');
 if(await page.locator('#sdl-graphics-fixes').isChecked())throw Error('FEX must start with original graphics libraries');
 await page.evaluate(async()=>{window.graphicsReport={active_version:'3.4.16',action:'updated_known_tazuo_5.2_pair'};await refresh();});
 await page.waitForFunction(()=>document.getElementById('sdl-graphics-status').textContent.includes('3.4.16 active'));
 await page.evaluate(async()=>{window.graphicsReport={active_version:'unrecognized',action:'unchanged_unrecognized_libraries'};await refresh();});
 await page.waitForFunction(()=>document.getElementById('sdl-graphics-status').textContent.includes('left as imported'));
 await page.evaluate(()=>localStorage.setItem('launch',JSON.stringify({managed_diagnostics:true,render_trace:true,sdl_graphics_fixes:true,client_memory_compatibility:true,renderer:'turnip',resolution:'1280x720',presentation_mode:'native_surface',display_fps:60,audio:false,gump_space:true})));
 await page.reload();await page.locator('[data-tab="client"]').click();
 if(await page.locator('#client-options').evaluate(node=>node.open))throw Error('Client options must start collapsed');
 await page.locator('#client-options > summary').click();
 if(await page.locator('#render-trace').isChecked()||await page.locator('#managed-diagnostics').isChecked()||await page.locator('#sdl-graphics-fixes').isChecked())throw Error('Legacy runtime experiments must reset');
 if(await page.locator('#fps').inputValue()!=='30')throw Error('Old transport-only 60 target must migrate to cooler default');
 if(await page.locator('#audio').isChecked()||await page.locator('#presentation').inputValue()!=='native_surface'||!await page.locator('#gump-space').isChecked())throw Error('Upgrade must preserve unrelated options');
 await page.locator('#resolution').selectOption('800x600');
 if(await page.locator('#gump-space').isChecked())throw Error('Other resolutions must opt out of fixed layout');
 await page.locator('#gump-space').check();
 if(await page.locator('#resolution').inputValue()!=='1280x720')throw Error('Gump space must select full 1280 canvas');
 await page.reload();await page.locator('[data-tab="client"]').click();
 if(await page.locator('#client-options').evaluate(node=>node.open))throw Error('Client options must start collapsed');
 await page.locator('#client-options > summary').click();
 if(!await page.locator('#gump-space').isChecked())throw Error('Layout selection did not persist');
 await page.locator('[data-action="client_start"]').click();await page.waitForTimeout(50);
 if(!await page.evaluate(()=>window.calls.some(c=>c.op==='client_start'&&c.args.runtime_backend==='fex-arm64ec-1'&&c.args.managed_diagnostics===false&&c.args.render_trace===false&&c.args.sdl_graphics_fixes===false&&c.args.audio_driver==='wasapi'&&c.args.proot_acceleration===true&&c.args.music_cache===true&&c.args.frame_budget===true&&c.args.smooth_audio===true)))throw Error('Default options missing from native launch');
 await page.locator('#fps').selectOption('60');
 await page.locator('#audio-driver').selectOption('directsound');
 await page.locator('#client-acceleration').uncheck();
 await page.locator('#music-cache').uncheck();
 await page.locator('#frame-budget').uncheck();
 await page.locator('#smooth-audio').uncheck();
 await page.locator('#render-trace').check();
 await page.locator('#managed-diagnostics').check();
 await page.locator('#sdl-graphics-fixes').uncheck();
 await page.reload();await page.locator('[data-tab="client"]').click();
 if(await page.locator('#client-options').evaluate(node=>node.open))throw Error('Client options must start collapsed');
 await page.locator('#client-options > summary').click();
 if(await page.locator('#sdl-graphics-fixes').isChecked())throw Error('Original graphics library choice did not persist');
 if(await page.locator('#fps').inputValue()!=='60')throw Error('Explicit 60 FPS choice must persist');
 if(!await page.locator('#render-trace').isChecked())throw Error('Render trace choice did not persist');
 await page.locator('[data-action="client_start"]').click();await page.waitForTimeout(50);
 if(!await page.evaluate(()=>window.calls.some(c=>c.op==='client_start'&&c.args.runtime_backend==='fex-arm64ec-1'&&c.args.managed_diagnostics===true&&c.args.render_trace===true&&c.args.sdl_graphics_fixes===false&&c.args.audio_driver==='directsound'&&c.args.proot_acceleration===false&&c.args.music_cache===false&&c.args.frame_budget===false&&c.args.smooth_audio===false)))throw Error('Selected options missing from native launch');
 if(!await page.evaluate(()=>JSON.parse(localStorage.getItem('launch')).gump_space))throw Error('Launch option missing');
 await page.screenshot({path:'ui-reports/client-landscape.png',fullPage:true});
 await page.setViewportSize({width:412,height:915});await page.screenshot({path:'ui-reports/client-phone.png',fullPage:true});
 for(const tab of ['realm','client','saves','journal']){
  await page.locator(`[data-tab="${tab}"]`).click();
  if(!await page.evaluate(tab=>document.body.dataset.scene===tab&&getComputedStyle(document.querySelector('#'+tab+' .scene-card')).backgroundImage.includes('background-'+tab+'.png'),tab))throw Error(tab+' background missing');
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error(tab+' overflows narrow viewport');
 }
 // A held native Play request owns startup; every competing mutation stays disabled.
 await page.locator('[data-tab="realm"]').click();
 await page.evaluate(()=>{window.calls=[];window.holdSession=true;window.nativeReport={session_busy:false};});
 await page.locator('[data-action="session_play"]').click();
 await page.waitForFunction(()=>!!window.heldSession);
 if(!await page.locator('[data-action="session_play"]').isDisabled()||!await page.locator('[data-action="server_start"]').isDisabled())throw Error('Concurrent launch controls remain enabled');
 await page.evaluate(async()=>{await refresh();document.querySelector('[data-action="server_start"]').click();});
 await page.waitForFunction(()=>document.getElementById('session-status').textContent.includes('waiting for the world'));
 if(!await page.locator('[data-action="session_cancel"]').isEnabled()||!await page.locator('[data-action="session_cancel"]').isVisible())throw Error('Launch cancellation is unavailable while Play owns the session');
 if(await page.evaluate(()=>window.calls.some(c=>c.op==='server_start'||c.op==='client_start')))throw Error('UI dispatched competing native startup');
 if(!await page.evaluate(()=>window.calls.some(c=>c.op==='session_play'&&c.args.runtime_backend==='fex-arm64ec-1'&&c.args.display_fps===60&&c.args.smooth_audio===false)))throw Error('Play did not preserve selected launch options');
 await page.evaluate(()=>{window.holdSession=false;window.nativeReport={session_busy:false};window.nativeReply(window.heldSession,{ok:true,result:{message:'Your world is ready.'}});});
 await page.waitForFunction(()=>!document.querySelector('[data-action="session_play"]').disabled);
 // Failed prerequisites reveal the right setup section and never try to open a display.
 await page.evaluate(()=>{window.calls=[];window.sessionFailure='Open Client setup and install the FEX client runtime first';});
 await page.locator('[data-action="session_play"]').click();
 await page.waitForFunction(()=>document.getElementById('client-setup').open&&document.getElementById('notice').classList.contains('error'));
 if(!await page.locator('#client').evaluate(node=>node.classList.contains('active')))throw Error('Client setup error did not select Client tab');
 if(await page.evaluate(()=>window.calls.some(c=>c.op==='client_view'||c.op==='client_start')))throw Error('Failed startup opened the client');
 await page.evaluate(()=>{window.sessionFailure='';window.realmReport={running:true,ready:false};});
 await page.waitForFunction(async()=>{await refresh();return document.getElementById('server-badge').textContent==='SERVER STARTING';});
 await page.evaluate(()=>{window.realmReport={running:true,ready:true};});
 await page.waitForFunction(async()=>{await refresh();return document.getElementById('server-badge').textContent==='SERVER ONLINE';});
 // The archive catalog survives an empty job list and a closed runtime.
 await page.evaluate(()=>{window.realmReport={running:false,ready:false,jobs:[]};window.nativeReport={alive:false,session_busy:false};});
 await page.locator('[data-tab="saves"]').click();
 await page.waitForFunction(()=>document.querySelectorAll('.backup-card').length===2);
 await page.evaluate(async()=>{await refresh();await refresh();});
 if(await page.locator('.backup-card').count()!==2)throw Error('Persistent archive inventory lost or duplicated');
 if(!await page.locator('.backup-card .exported').count()||!await page.locator('.backup-card .not-exported').count())throw Error('Export status missing');
 await page.locator('.backup-card').first().getByRole('button',{name:'Preview / restore'}).click();
 if(!await page.locator('#restore-preview').isVisible()||!await page.locator('#restore-folders').textContent().then(text=>text.includes('Info, Saves, Backups')))throw Error('Restore preview missing');
 await page.screenshot({path:'ui-reports/restore-phone.png',fullPage:true});
 await page.locator('#cancel-restore').click();
 if(await page.evaluate(()=>window.calls.some(call=>call.op==='restore_world')))throw Error('Preview cancellation changed the world');
 await page.locator('[data-tab="realm"]').click();await page.locator('#server-settings > summary').click();
 await page.waitForSelector('#setting-S_ServerSaveMinutes');
 await page.locator('#setting-S_ServerSaveMinutes').fill('45');
 await page.waitForFunction(()=>document.getElementById('settings-dirty').textContent.includes('1 unsaved'));
 await page.locator('[data-action="settings_save"]').click();
 await page.waitForFunction(()=>window.calls.some(call=>call.op==='settings_save'&&call.args.changes.S_ServerSaveMinutes===45));
 await page.waitForFunction(()=>document.getElementById('settings-dirty').textContent==='No unsaved changes.');
 if(!await page.locator('[data-action="settings_undo"]').isEnabled())throw Error('Undo not available after settings save');
 await page.locator('#settings-search').fill('skill');
 if(await page.locator('.setting-field:not([hidden])').count()===0)throw Error('Settings search has no results');
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Settings editor overflows phone viewport');
 await page.screenshot({path:'ui-reports/settings-phone.png',fullPage:true});
 await page.evaluate(()=>{window.nativeReport={alive:true,session_busy:false};window.realmReport={running:true,ready:true,jobs:[]};});
 await page.locator('#settings-search').fill('');await page.locator('#setting-S_ServerSaveMinutes').fill('50');
 await page.waitForFunction(async()=>{await refresh();return document.querySelector('[data-action="settings_save"]').disabled;});
 if(!await page.locator('[data-action="settings_save"]').isDisabled())throw Error('Settings can be applied while server is running');
 await page.locator('[data-action="settings_reset"]').click();
 await page.locator('[data-tab="saves"]').click();await page.screenshot({path:'ui-reports/saves-phone.png',fullPage:true});
 await page.locator('.backup-card').first().getByRole('button',{name:'Preview / restore'}).click();
 await page.locator('#confirm-restore').click();await page.waitForFunction(()=>window.calls.some(call=>call.op==='restore_world'));
 if(!await page.evaluate(()=>{const close=window.calls.findIndex(call=>call.op==='session_close'),restore=window.calls.findIndex(call=>call.op==='restore_world');return close>=0&&restore>close;}))throw Error('Restore did not save and close the session first');
 await page.waitForFunction(()=>!document.getElementById('restore-preview').open);
 // Cancel Play uses the dedicated shutdown action while ordinary mutations stay locked.
 await page.evaluate(()=>{window.holdSession=true;window.nativeReport={alive:true,session_busy:false};window.realmReport={running:false,ready:false,jobs:[]};window.mockJobs=[];});
 await page.locator('[data-action="session_play"]').click();
 await page.waitForFunction(async()=>{await refresh();return !document.querySelector('[data-action="session_cancel"]').hidden;});
 await page.locator('[data-action="session_cancel"]').click();
 await page.waitForFunction(()=>window.calls.some(call=>call.op==='session_cancel')&&!document.querySelector('[data-action="session_play"]').disabled);
 await page.evaluate(()=>{window.realmReport={running:false,ready:false,jobs:[]};document.getElementById('client-options').open=false;document.getElementById('client-setup').open=false;});
 await page.locator('[data-tab="client"]').click();await page.screenshot({path:'ui-reports/client-phone-collapsed.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Collapsed client view overflows phone viewport');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('Collapsed client options, saved defaults, guarded Play and setup errors, server readiness, archive links, and phone/landscape layouts passed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
