"""Developer-only generation after exact map patcher and structural verification.

Requires bsdiff4; normal qualification verifies the committed deltas and never
regenerates them. No complete vendor assemblies are stored in the repository.
"""
from pathlib import Path
import base64
import hashlib
import sys
import bsdiff4

sys.path.insert(0, str(Path(__file__).resolve().parent.parent/'backend'))
import client_render_trace as trace

work = Path('runtime-work/map-metadata-fixture')
rows = []
labels = {
    ('ordinary', 'TazUO.dll'): 'client',
    ('ordinary-render', 'TazUO.dll'): 'client-render',
    ('resource', 'TazUO.dll'): 'client-resource',
    ('resource-render', 'TazUO.dll'): 'client-resource-render',
    ('ordinary', 'ClassicUO.Assets.dll'): 'assets-music',
    ('ordinary-render', 'ClassicUO.Assets.dll'): 'assets',
    ('resource', 'ClassicUO.Assets.dll'): 'assets-resource-music',
    ('resource-render', 'ClassicUO.Assets.dll'): 'assets-resource',
}
for variant in ('ordinary', 'ordinary-render', 'resource', 'resource-render'):
    for name in ('TazUO.dll', 'ClassicUO.Assets.dll'):
        before = (work/('base-'+variant)/name).read_bytes()
        after = (work/('patched-'+variant)/name).read_bytes()
        patch = bsdiff4.diff(before, after)
        assert trace.apply_delta(before, patch) == after
        filename = 'tazuo-5.2-map-metadata-'+labels[variant,name]+'.patch.b64'
        Path('backend', filename).write_bytes(base64.b64encode(patch))
        row = name, hashlib.sha256(before).hexdigest(), hashlib.sha256(after).hexdigest(), filename
        rows.append(row)
        print('MAP_METADATA_DELTA_CREATED', variant, name, row[1], row[2], filename, 'bytes='+str(len(patch)))
Path('backend/client_map_metadata_variants.py').write_text(
    '"""Exact verified chunk-metadata deltas; generated by generate-map-metadata-deltas.py."""\n\nVARIANTS = (\n' +
    ''.join('    '+repr(row)+',\n' for row in rows) + ')\n')
