/* name, exact Vulkan declaration, exact forwarded arguments, dispatch handle */
CALL(CreateShaderModule, (VkDevice device, const VkShaderModuleCreateInfo *info, const VkAllocationCallbacks *allocator, VkShaderModule *shader), (device, info, allocator, shader), device)
CALL(CreateGraphicsPipelines, (VkDevice device, VkPipelineCache cache, uint32_t count, const VkGraphicsPipelineCreateInfo *infos, const VkAllocationCallbacks *allocator, VkPipeline *pipelines), (device, cache, count, infos, allocator, pipelines), device)
CALL(CreateComputePipelines, (VkDevice device, VkPipelineCache cache, uint32_t count, const VkComputePipelineCreateInfo *infos, const VkAllocationCallbacks *allocator, VkPipeline *pipelines), (device, cache, count, infos, allocator, pipelines), device)
CALL(CreatePipelineCache, (VkDevice device, const VkPipelineCacheCreateInfo *info, const VkAllocationCallbacks *allocator, VkPipelineCache *cache), (device, info, allocator, cache), device)
CALL(CreatePipelineLayout, (VkDevice device, const VkPipelineLayoutCreateInfo *info, const VkAllocationCallbacks *allocator, VkPipelineLayout *layout), (device, info, allocator, layout), device)
CALL(CreateDescriptorSetLayout, (VkDevice device, const VkDescriptorSetLayoutCreateInfo *info, const VkAllocationCallbacks *allocator, VkDescriptorSetLayout *layout), (device, info, allocator, layout), device)
CALL(AllocateDescriptorSets, (VkDevice device, const VkDescriptorSetAllocateInfo *info, VkDescriptorSet *sets), (device, info, sets), device)
CALL(AllocateMemory, (VkDevice device, const VkMemoryAllocateInfo *info, const VkAllocationCallbacks *allocator, VkDeviceMemory *memory), (device, info, allocator, memory), device)
CALL(MapMemory, (VkDevice device, VkDeviceMemory memory, VkDeviceSize offset, VkDeviceSize size, VkMemoryMapFlags flags, void **data), (device, memory, offset, size, flags, data), device)
CALL(FlushMappedMemoryRanges, (VkDevice device, uint32_t count, const VkMappedMemoryRange *ranges), (device, count, ranges), device)
CALL(InvalidateMappedMemoryRanges, (VkDevice device, uint32_t count, const VkMappedMemoryRange *ranges), (device, count, ranges), device)
CALL(CreateImage, (VkDevice device, const VkImageCreateInfo *info, const VkAllocationCallbacks *allocator, VkImage *image), (device, info, allocator, image), device)
CALL(CreateImageView, (VkDevice device, const VkImageViewCreateInfo *info, const VkAllocationCallbacks *allocator, VkImageView *view), (device, info, allocator, view), device)
CALL(CreateBuffer, (VkDevice device, const VkBufferCreateInfo *info, const VkAllocationCallbacks *allocator, VkBuffer *buffer), (device, info, allocator, buffer), device)
CALL(BindImageMemory, (VkDevice device, VkImage image, VkDeviceMemory memory, VkDeviceSize offset), (device, image, memory, offset), device)
CALL(BindBufferMemory, (VkDevice device, VkBuffer buffer, VkDeviceMemory memory, VkDeviceSize offset), (device, buffer, memory, offset), device)
CALL(CreateSwapchainKHR, (VkDevice device, const VkSwapchainCreateInfoKHR *info, const VkAllocationCallbacks *allocator, VkSwapchainKHR *swapchain), (device, info, allocator, swapchain), device)
CALL(AcquireNextImageKHR, (VkDevice device, VkSwapchainKHR swapchain, uint64_t timeout, VkSemaphore semaphore, VkFence fence, uint32_t *index), (device, swapchain, timeout, semaphore, fence, index), device)
CALL(AcquireNextImage2KHR, (VkDevice device, const VkAcquireNextImageInfoKHR *info, uint32_t *index), (device, info, index), device)
CALL(QueueSubmit, (VkQueue queue, uint32_t count, const VkSubmitInfo *submits, VkFence fence), (queue, count, submits, fence), queue)
CALL(QueueSubmit2, (VkQueue queue, uint32_t count, const VkSubmitInfo2 *submits, VkFence fence), (queue, count, submits, fence), queue)
CALL(QueueSubmit2KHR, (VkQueue queue, uint32_t count, const VkSubmitInfo2 *submits, VkFence fence), (queue, count, submits, fence), queue)
CALL(QueuePresentKHR, (VkQueue queue, const VkPresentInfoKHR *info), (queue, info), queue)
CALL(WaitForFences, (VkDevice device, uint32_t count, const VkFence *fences, VkBool32 all, uint64_t timeout), (device, count, fences, all, timeout), device)
CALL(WaitSemaphores, (VkDevice device, const VkSemaphoreWaitInfo *info, uint64_t timeout), (device, info, timeout), device)
CALL(WaitSemaphoresKHR, (VkDevice device, const VkSemaphoreWaitInfo *info, uint64_t timeout), (device, info, timeout), device)
CALL(QueueWaitIdle, (VkQueue queue), (queue), queue)
CALL(DeviceWaitIdle, (VkDevice device), (device), device)
CALL(CreateCommandPool, (VkDevice device, const VkCommandPoolCreateInfo *info, const VkAllocationCallbacks *allocator, VkCommandPool *pool), (device, info, allocator, pool), device)
CALL(AllocateCommandBuffers, (VkDevice device, const VkCommandBufferAllocateInfo *info, VkCommandBuffer *buffers), (device, info, buffers), device)
CALL(BeginCommandBuffer, (VkCommandBuffer buffer, const VkCommandBufferBeginInfo *info), (buffer, info), buffer)
CALL(EndCommandBuffer, (VkCommandBuffer buffer), (buffer), buffer)
CALL(ResetCommandBuffer, (VkCommandBuffer buffer, VkCommandBufferResetFlags flags), (buffer, flags), buffer)
